### ISSUE TITLE
it say the program is not a linux  program

### ISSUE THREAD

**Issue by DeviateBacon3** [ThioJoe/YouTube-Spammer-Purge#106]
**IS THIS A FEATURE REQUEST OR IDEA? SUBMIT A DISCUSSION POST INSTEAD HERE: https://github.com/ThioJoe/YouTube-Spammer-Purge/discussions**

**Describe the bug**

**Operating System You're Using: (Windows, Mac, Linux?)**

**Release Version:**

**Steps To Reproduce**
Steps leading up to the problem.

**Expected behavior (if not obvious):**

**Paste and Displayed Error Messages & 'Tracebacks' **

**Other questions that might apply**
- Does the issue happen every time or only sometimes?
- Have you tried an older release, and does it happen there too?
- Have you tried anything that changes / affects the error?

**Additional context**
Add any other context you want to add about the problem here.

**Comment by DeviateBacon3** [comment]
i need the .deb for it to work

**Comment by ThioJoe** [comment]
The template is there for a reason
