### ISSUE TITLE
Github CodeQL failed

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YouTube-Spammer-Purge#111]
**Describe the bug**
The github CodeQL failed, idk what it is or if its a concern but just want to bring it to your notice @ThioJoe 

**Release Version:**
Current Release

**Paste and Displayed Error Messages & 'Tracebacks'**
https://user-images.githubusercontent.com/84712013/144832077-d78d4403-0e0e-46f3-a0a4-a5e74c4d7920.png

**Additional context**
Link to error https://github.com/ThioJoe/YouTube-Spammer-Purge/runs/4420415066

**Comment by TechStudent11** [comment]
It's nothing. It's just that ThioJoe is storing "sensitive information" aka the username.

**Comment by KendallDoesCoding** [comment]
Oh ok, I didn't understand what it meant and just wanted to give a heads up...
