### ISSUE TITLE
Output Error Fixed + Another Error

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YouTube-Spammer-Purge#116]
**Describe the bug**
Error outputting code

**Operating System You're Using: (Windows, Mac, Linux?)**
Gitpod, VS Code in Browser

**Release Version:**
Current Github Version

**Steps To Reproduce**
Steps leading up to the problem.

**Expected behavior (if not obvious):**

**Paste and Displayed Error Messages & 'Tracebacks' **
 File "/workspace/YouTube-Spammer-Purge/YouTubeSpammerPurge.py", line 42, in <module>
    from gui import *
  File "/workspace/YouTube-Spammer-Purge/gui.py", line 5, in <module>
    import YouTubeSpammerPurge as myFunctions
  File "/workspace/YouTube-Spammer-Purge/YouTubeSpammerPurge.py", line 58, in <module>
    import rtfunicode
ModuleNotFoundError: No module named 'rtfunicode'

**Comment by ynsnf** [comment]
Type "pip install rtfunicode" in your cli and try again. Check requirements.txt

**Comment by KendallDoesCoding** [comment]
Thanks, will do that, I'm running it on Gitpod so maybe that's the issue. Was just experimenting around

**Comment by KendallDoesCoding** [comment]
File "/workspace/YouTube-Spammer-Purge/YouTubeSpammerPurge.py", line 42, in <module>
    from gui import *
  File "/workspace/YouTube-Spammer-Purge/gui.py", line 5, in <module>
    import YouTubeSpammerPurge as myFunctions
  File "/workspace/YouTube-Spammer-Purge/YouTubeSpammerPurge.py", line 62, in <module>
    from googleapiclient.errors import HttpError
ModuleNotFoundError: No module named 'googleapiclient'

**Comment by KendallDoesCoding** [comment]
pip install google-api-python-client

**Comment by ThioJoe** [comment]
Should be able to be solved in the future by using 
`pip install -r requirements.txt`

**Comment by KendallDoesCoding** [comment]
> Should be able to be solved in the future by using `pip install -r requirements.txt`

Ok thanks, then I will edit my pull request too #118
