### ISSUE TITLE
i try

### ISSUE THREAD

**Issue by DeviateBacon3** [ThioJoe/YouTube-Spammer-Purge#129]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**

### What happened?

I try on Windows it give me OS not compatible

### Release version

1.6.1

### Steps to reproduce

open the application
click allow install on Windows
and then says failed to install your windows version is incompatible.

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
Windows version incompatible
```

**Comment by KendallDoesCoding** [comment]
Please share a screenshot of the output @DeviateBacon3 , did you try running the code or did you try running the .exe?

**Comment by KendallDoesCoding** [comment]
Please edit the title of this issue to - Not compatible on Windows @DeviateBacon3

**Comment by KendallDoesCoding** [comment]
It worked just fine for me @DeviateBacon3 , what kind of laptop/pc do you have, if its a old model, it may be a genuine issue.

**Comment by TechStudent11** [comment]
I don't think you have a compatible version of Python.

**Comment by KendallDoesCoding** [comment]
> I don't think you have a compatible version of Python.

Yeah, please download the newest version of python, from their website.

**Comment by TechStudent11** [comment]
@DeviateBacon3 @KendallDoesCoding https://python.org

**Comment by KendallDoesCoding** [comment]
@ThioJoe , please close this. Is python version or computer isnt compatible.

**Comment by ThioJoe** [comment]
Closing because no requested helpful info given
