### ISSUE TITLE
[Bug]: (Scan Mode Issue)

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YouTube-Spammer-Purge#136]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**

### What happened?

I was trying to run the code on https://replit.com/ to test if it works, because of my PR #118 when I got this error, I believe it isn't because I am running to code on replit, but I think it's a code error.

### Release version

1.6.1

### Steps to reproduce

1.  Pip install
2. Run code

### Relevant log output

```shell
File "YouTubeSpammerPurge.py", line 1815
    match scanMode:
          ^
SyntaxError: invalid syntax
```

**Comment by KendallDoesCoding** [comment]
@ThioJoe I think this issue has to do with the newest commit https://github.com/ThioJoe/YouTube-Spammer-Purge/commit/f882260201658dad68a256b610170b6bc789ae36

**Comment by KendallDoesCoding** [comment]
I think the commit fixed the issue actually, I had a previous version of the code open.

**Comment by ThioJoe** [comment]
It was because the match feature requires python 3.10. I removed it and put the if statements back so it shouldn't be a problem now.

**Comment by KendallDoesCoding** [comment]
Yup, its fixed now, that's why I closed the issue!
