### ISSUE TITLE
[Bug]: (Enter short, one sentence summary of bug here)

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YouTube-Spammer-Purge#137]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**

### What happened?

I was trying to see if I could fix #136, so I took the code to this website - https://extendsclass.com/python-tester.html, when it told me a syntax error in this code, not what I needed to fix, and I don't think this is interfering with the code, but just review it and see what yall can do.

### Release version

1.6.1

### Steps to reproduce

1. Go to https://extendsclass.com/python-tester.html
2.  Paste code
3.  Error output

### Relevant log output

```shell
Line 159:
print(f"{F.LIGHTMAGENTA_EX}---------------------------- Match Samples: One comment per matched-comment author ----------------------------{S.R}")
^
SyntaxError: invalid syntax
```

**Comment by ThioJoe** [comment]
I think it's wrong

**Comment by KendallDoesCoding** [comment]
> I think it's wrong. Closing because doesn't seem to be causing issues in real world.

Yes. I just wanted to give you a heads up on the issue, but it isnt causing any interreference.
