### ISSUE TITLE
[Bug]: (sys not defined)

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YouTube-Spammer-Purge#138]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**

### What happened?

I was trying to run the code on Gitpod and got this issue, Although I am not very sure if this is because I am running it on gitpod or if it is a genuine issue.

### Release version

1.6.1

### Steps to reproduce

1. Pip install requirements file
2. Run code

### Relevant log output

```shell
Traceback (most recent call last):
  File "YouTubeSpammerPurge.py", line 2289, in <module>
    main()
  File "YouTubeSpammerPurge.py", line 1672, in main
    if sys.version_info[0] < 3 or sys.version_info[1] < 6:
NameError: name 'sys' is not defined
```

**Comment by ThioJoe** [comment]
Pretty sure this is a problem with using Gitpod. You'll have to figure it out why it's not working with the script, it might be something you need to configure

**Comment by KendallDoesCoding** [comment]
@ThioJoe getting the same issue in anyfiddle.

No module named 'tkinter'

A module was not found try installing the requirements using either of these:
pip3 install -r requirements.txt
pip install -r requirements.txt
Traceback (most recent call last):
  File "/home/anyfiddle/project/YouTubeSpammerPurge.py", line 2289, in <module>
    main()
  File "/home/anyfiddle/project/YouTubeSpammerPurge.py", line 1672, in main
    if sys.version_info[0] < 3 or sys.version_info[1] < 6:
NameError: name 'sys' is not defined

**Comment by ThioJoe** [comment]
tkinter comes installed with python, so if it's not finding it then it's a problem with the platform
