### ISSUE TITLE
Don't Work

### ISSUE THREAD

**Issue by Skepis** [ThioJoe/YouTube-Spammer-Purge#140]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**

### What happened?

So i was trying to delete comments with this program but it didn't work and then i tried again but then it says Error

### Release version

1.6.1.0

### Steps to reproduce

First i tried to refresh youtube. Two tried again. Three got a error to contact to this website https://github.com/ThioJoe/YouTube-Spammer-Purge/issues

### What platform are you seeing this problem on?

Windows

**Comment by ThioJoe** [comment]
How do you expect me to help without telling me the actual error message

**Comment by Skepis** [comment]
> How do you expect me to help without telling me the actual error message

It's working now, it might lagged and then didn't delete the comments
