### ISSUE TITLE
{Bug} (Doesn't automatically add ThioJoe as a Reviewer for PR's)

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YouTube-Spammer-Purge#149]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**

### What happened?

To automatically add @ThioJoe as a reviewer for PR's we need to install this app to this project- https://github.com/apps/auto-assign and do as it says in the app details.

### Steps to reproduce

1.  Create a PR

### What platform are you seeing this problem on?

Windows

**Comment by KendallDoesCoding** [comment]
This isn't really a project issue, but I couldnt create a PR, to make yall install the app, so I made issue.

**Comment by ThioJoe** [comment]
Eh this doesn't matter

**Comment by KendallDoesCoding** [comment]
> Eh this doesn't matter

Yeah, but it does add a nice touch to the code, if it's there. Anyways, I think @TechStudent11 is working on this and a updated PR template.
