### ISSUE TITLE
Idea, spam account block list

### ISSUE THREAD

**Issue by ageekhere** [ThioJoe/YouTube-Spammer-Purge#15]
I wonder if a community run spammer account list could be created. People could submit known bots to the list and have their messages auto deleted.

**Comment by MDP43140** [comment]
@ageekhere yeah that's good idea

**Comment by avighnac** [comment]
That is a good idea but new spam account will keep being created.

**Comment by joaogelado** [comment]
> That is a good idea but new spam accounts will keep being created. 

But, before they figure out, it would be very effective

**Comment by avighnac** [comment]
True. This should be done.

**Comment by ageekhere** [comment]
Maybe the script could even have an option to ban the bots that are in the list as well as deleting all their comments.

**Comment by deidyomega** [comment]
If there is interest and @ThioJoe is cool with it, I could add that functionality
