### ISSUE TITLE
[Bug]: (Blank screen when trying to run code)

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YouTube-Spammer-Purge#150]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**

### What happened?

I was trying to run the .exe file, but I cannot run the file, nor can I type and input anything.

![image](https://user-images.githubusercontent.com/84712013/145767566-9b193e57-189b-4485-8382-42ce3991712b.png)

### Steps to reproduce

1. Run .exe file on Windows

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
None, I just can see a blank screen.
```

**Comment by ThioJoe** [comment]
If you let it sit there long enough does anything eventually show up?

**Comment by KendallDoesCoding** [comment]
> If you let it sit there long enough does anything eventually show up?

I think its because of my antivirus software... It worked on my laptop, after I went through a process in my antivirus, idk why it didnt work on my desktop. I'll try disabling the antivirus for 5minutes while I try running the program tomorrow. Closing this for now.

**Comment by ThioJoe** [comment]
Yea the fact that it doesn't even get to the point of displaying "loading" means something is stopping it really early on.

**Comment by KendallDoesCoding** [comment]
No, it's not because of my antivirus, I tried the beta and 1.6.1 while the antivirus was turned off and still blank.

**Comment by TechStudent11** [comment]
you need a client secrets file

**Comment by KendallDoesCoding** [comment]
First if you didnt have the file it gave a error. And, when I got the blank
screen i did have client_secrets.json

**Comment by TechStudent11** [comment]
make sure it's valid. maybe generate a new one

**Comment by arnav56745** [comment]
#158

**Comment by KendallDoesCoding** [comment]
@arnav56745 Thanks. I'm currently not using a VPN on my computer though. But there was some issues with my chrome profile blocking some stuff. So maybe its not getting through to the API.

I think, i'm the only one, with @arnav56745 facing this problem so am closing this.

Thanks for your help.
