### ISSUE TITLE
It says error

### ISSUE THREAD

**Issue by arnav56745** [ThioJoe/YouTube-Spammer-Purge#158]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**

### What happened?

![image](https://user-images.githubusercontent.com/96387132/146683672-d8baba79-9ab0-417e-b33c-118935957ad0.png)

### Release version

2.0.0Beta3

### Steps to reproduce

1. Run .exe file

### What platform are you seeing this problem on?

Windows 10 2021(HP desktop)

### Relevant log output

Error: Expected value on line 1, column 1
### Path
C:\Users\[User]\Favorites\Downloads\New folder

**Comment by arnav56745** [comment]
I tried everything i can, deleting 'token.pickle'

**Comment by arnav56745** [comment]
Its much better to delete comments manually

**Comment by ThioJoe** [comment]
You joined GitHub just to post this but then couldn't wait more than a literal 10 minutes for help? Bruh.

Anyway, based on the traceback, the problem occurs as the request is being made to the YouTube API to authenticate.  The API apparently has returned a blank response. After some searching, one possible reason is that the API is blocking your IP, so if you have a VPN maybe try that, or if you're using a VPN, try without it. 

It could also be a temporary transient error on the backend of the API that will fix itself.

**Comment by arnav56745** [comment]
### More issues
1. if you open the file normally, it will not open.

**Comment by arnav56745** [comment]
also, i do not have vpn enabled, so what is the problem?
image:
![image](https://user-images.githubusercontent.com/96387132/146712736-f7472c0f-8091-433f-ab27-715b69f9fe1e.png)
![image](https://user-images.githubusercontent.com/96387132/146712793-59c2ec80-bf5e-4aea-8aaf-5111c2e09120.png)

**Comment by arnav56745** [comment]
If my VPN isn't enabled, so how can't the yt API authenticate?

**Comment by arnav56745** [comment]
*not

**Comment by arnav56745** [comment]
@ThioJoe

**Comment by TechStudent11** [comment]
@arnav56745 Try following the steps again.

**Comment by ThioJoe** [comment]
I honestly have no idea 🤷‍♂️

**Comment by arnav56745** [comment]
but it says that you need a client secrets.json file.
also, i do have client secrets.json file

**Comment by TechStudent11** [comment]
It needs to be named `client_secrets.json` and has to be in the same folder as the `YouTubeSpammerPurge.py` file.

**Comment by TechStudent11** [comment]
https://github.com/ThioJoe/YouTube-Spammer-Purge#instructions---obtaining-youtube-api-key
