### ISSUE TITLE
[Bug]: config file creation crash

### ISSUE THREAD

**Issue by Kurdakov** [ThioJoe/YouTube-Spammer-Purge#161]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When creating a config file with versions 2 and 2.1 for some reason (possibly I use several encodings installed on my PC (Windows 10 English with Russian support)) I get error 

Choice (1-5): 3
Traceback (most recent call last):
  File "C:\YouTube-Spammer-Purge\YoutubeSpammerPurge.py", line 1359, in create_config_file
    parser.read("SpamPurgeConfig.ini")
  File "C:\Python39\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Python39\lib\configparser.py", line 1020, in _read
    for lineno, line in enumerate(fp, start=1):
  File "C:\Python39\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 4233: character maps to <undefined>
Something went wrong when checking the created file. Check if SpamPurgeConfig.ini exists and has text. The info above may help if it's a bug.

replacing string
1359:  parser.read("SpamPurgeConfig.ini") 
to
parser.read("SpamPurgeConfig.ini", 'utf-8') 

fixes this error.

### Release version

2.1

### Steps to reproduce

1. Create or replace config file via option 3 of the program
2. crash

### What platform are you seeing this problem on?

Windows

**Comment by ThioJoe** [comment]
Hm yea looks like specifying the encoding will fix it, I'll add a fix with a new release

**Comment by ThioJoe** [comment]
Should be fixed as of release 2.2.1
