### ISSUE TITLE
[Bug]: Not detecting tkinter as installed

### ISSUE THREAD

**Issue by BaterWucket** [ThioJoe/YouTube-Spammer-Purge#169]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to start the script, but it did reply to me with this 

`Traceback (most recent call last):
  File "/home/baterwucket/Videos/YouTube-Spammer-Purge-main/YouTubeSpammerPurge.py", line 43, in <module>
    from gui import *
  File "/home/baterwucket/Videos/YouTube-Spammer-Purge-main/gui.py", line 13, in <module>
    from tkinter import Menu, TclError, Tk, Canvas, Entry, Text, Button, PhotoImage
ModuleNotFoundError: No module named 'tkinter'
`

I tried installing Tkinter but idk whats the issue

### Release version

-cant check, most recent -

### Steps to reproduce

Well this section is complicated
1. I ran `python3 YouTubeSpammerPurge.py`
2. It responded with  **error**

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/baterwucket/Videos/YouTube-Spammer-Purge-main/YouTubeSpammerPurge.py", line 43, in <module>
    from gui import *
  File "/home/baterwucket/Videos/YouTube-Spammer-Purge-main/gui.py", line 13, in <module>
    from tkinter import Menu, TclError, Tk, Canvas, Entry, Text, Button, PhotoImage
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by ThioJoe** [comment]
Tkinter should come with Python. If you're using a python install that came with the OS, you might have to install it yourself.

**Comment by BaterWucket** [comment]
Ok I will try to install it separately

**Comment by BaterWucket** [comment]
ok i installed tkinter and it works if someone is interested I used command `sudo apt-get install python3-tk`
