### ISSUE TITLE
Error with Japanese unicodes

### ISSUE THREAD

**Issue by NotDreppy** [ThioJoe/YouTube-Spammer-Purge#17]
When displaying comments with Japanese words, some of them will be seen as Unicode. But during the converting process, an issue occurred. The program crashed and it says cp950 codec can't encode character \U0001354. Please add support for Japanese or comments in other languages.

**Comment by rk0cc** [comment]
I'm also concern about Korean and Chinese which called CJK that those characters is the same area in Unicode.

**Comment by avighnac** [comment]
Steps to reproduce?

**Comment by ThioJoe** [comment]
Hm can you copy and paste some of the comments with these characters to test on?

Also can you see if running the program without logging to file enabled and see if that makes it work? 

Trying to figure out where it crashes.

Also the exact output of the entire error would be helpful

**Comment by ThioJoe** [comment]
Should be fixed with latest release v1.3.3 and as of commit https://github.com/ThioJoe/YouTube-Spammer-Purge/commit/7a607e28135bb1c7149f311f47e13e0039b6d854
