### ISSUE TITLE
[Bug]: Avast One reporting YouTube Spammer Purge app as malware

### ISSUE THREAD

**Issue by bigmancallum** [ThioJoe/YouTube-Spammer-Purge#171]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I tried to launch the app, but Avast One flagged it up as malware (Win64:Evo-gen [Susp]) and moved it to its Quarantine feature.

![image](https://user-images.githubusercontent.com/47284263/147143266-9b7ac8e6-c034-4a1b-899d-0e33ae407b10.png)
![image](https://user-images.githubusercontent.com/47284263/147143380-c38944de-0bad-4c4e-b7a3-7698e995639c.png)

### Release version

2.2.2

### Steps to reproduce

1. Download the exe.
2. Open the exe.
3. Avast One flags it and doesn't let you run it.

### What platform are you seeing this problem on?

Windows

**Comment by ThioJoe** [comment]
oof, ok I've submitted it to Avast for review. Quite frustrating because I always submit it to Virustotal to make sure there are no false positives before release: https://www.virustotal.com/gui/file/4a39911b72309e9c1895a96e5de1405934e3c8e891cdaa43258b238328eab649

**Comment by bigmancallum** [comment]
> oof, ok I've submitted it to Avast for review. Quite frustrating because I always submit it to Virustotal to make sure there are no false positives before release: https://www.virustotal.com/gui/file/4a39911b72309e9c1895a96e5de1405934e3c8e891cdaa43258b238328eab649

That's fine lol, I created an exeption in Avast One and can now run it.
