### ISSUE TITLE
Error 403 Access Denied When Trying To Log In With Google Acount

### ISSUE THREAD

**Issue by MemeBoy92** [ThioJoe/YouTube-Spammer-Purge#172]
After I set up the application and API key on mac, when I tried to sign in with my google account it said access denied
<img width="1191" alt="Screen Shot 2021-12-22 at 12 32 27 PM" src="https://user-images.githubusercontent.com/79237217/147152023-7bebdd9f-a9f1-43de-b7b0-e957bc1bb18a.png">
.

**Comment by ThioJoe** [comment]
Sometimes you need to add yourself as a 'test user' to get permissions. 
Have you tried Step 14 from the instructions in the Readme here?: https://github.com/ThioJoe/YouTube-Spammer-Purge#instructions---obtaining-youtube-api-key

**Comment by MemeBoy92** [comment]
Forgot that step. Works perfectly, thank you!
