### ISSUE TITLE
[Bug]: Unable to detect comments in other languages (such as Portuguese) or copypastas with absurd texts (such as allowing sexual abuse)

### ISSUE THREAD

**Issue by abUwUser** [ThioJoe/YouTube-Spammer-Purge#176]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to check if this program could detect in other languages, and it failed when i tried in one of Felipe Neto's videos. I was suprised by that because it should have detected it, considering that it is a 43mi channel. I am suprised since some of the comments have an emoji abuse. As a suggestion, if needed verification of the video's lang it could see the first 5 messages and translate in an online API or something. I know that maybe it will require asking for an key, but you can add an optional setting to ask for translation

### Comparasion
* One of PewDiePie's video (https://www.youtube.com/watch?v=qzRIc14LC9U) - Found 36
![Console](https://user-images.githubusercontent.com/27961224/147159211-f9c8cdb5-ee31-48b5-9b74-39da8935c1f9.png)
![Found comment](https://user-images.githubusercontent.com/27961224/147158905-435e7e12-b64e-4344-a716-429afa59246d.png)
<br />

* One of Felipe Neto's video (https://www.youtube.com/watch?v=0LdNu1j2iEM) - Found none
![Console](https://user-images.githubusercontent.com/27961224/147159990-307d0a0e-3cc7-423a-9192-b552f2ed6e9a.png)
![Found comment](https://user-images.githubusercontent.com/27961224/147159498-a9bc68b2-7cca-4a8f-921b-e51919529dc7.png)
<sub>Translated message from "Trøllmanagem ᵐⁱˡ ᵍʳᵃᵘ #BolsoLula2022": `HUNDREDS OF CHILDREN ARE RAPED EVERY DAY, WELL DONE 👍😂, WHO HAS THE BOLSOLULA CRITICIZED?? 😂😂😂🤣😂🤣🤣🤣🤣🤣😂🤣😂🤣😂🤣👍🤣😂🤣😂🤣🤣😂🤣😂🤣😂🤣😂🤣👍🤣👍🤣👍🤣👍🤣👍🤣👍🙏👍🤣👍👍🤣👍👌 👍👌😂🤣👍🤣😂🤣😂🤣🤣👍🤣👍🤣👍🤣👍🤣👍🤣👍`</sub>
Note that "Trøllmanagem ᵐⁱˡ ᵍʳᵃᵘ #BolsoLula2022" is trolling. Dont take this seriously. And he is being politic and spamming everywhere on Felipe Neto's channel.
<br />

* The 5 latest whinderssonnunes' videos as for now - Found 1, and it is a false alert by context
![image](https://user-images.githubusercontent.com/27961224/147161135-2ec4abb5-a639-42df-bac5-20870ed2d279.png)
<sub>Translated message from "Mia 👈𝐹**СК МЕ - СНЕ𝒞𝒦 𝑀𝒴 Р𝑅𝟢𝐹𝐼𝐿Е          ": `The world started to get back to normal after I realized that Whindersson returned to post video`</sub>
<br />

* The last 5 Diggo's videos as for now - Found 6, but looking at them they're false alerts
![image](https://user-images.githubusercontent.com/27961224/147163177-6cb23a10-8779-411b-a477-13cc2f27b1fc.png)
<sub>Those were all translated in Google Translated:</sub>
<sub>1. Minecraft is a cool game, congratulations on recognizing it diggo!</sub>
<sub>2. Wow, it's complicated for you to make a video for nothing and without a lot of work and realize that this video is doing much better than a super well done and well edited song, we can't deny it, anyone would be shaken...</sub>
<sub>3. Carlos? you around here my friend</sub>
<sub>4. The Internet itself is very toxic, but tik tok is king in making many young people commit crimes and recording and posting tiko teko (?). It's amazing that, people get hurt, get hurt or comment crimes by modinha in tik tok, teenagers are mt idiots msm.</sub>
<sub>5. No idea man kk</sub>
<sub>6. I'm tired of it, all the time there are offensive troll comments to attack you, offend you. I can't take it anymore mn, the most comments are from these guys</sub>

### Release version

2.2.2

### Steps to reproduce

1. Open YTS
2. Do a scan in a channel that speaks a different language (tested in portuguese)
3. Check the results

### What platform are you seeing this problem on?

Windows

**Comment by abUwUser** [comment]
By the way, maybe I wont respond this. I am avaiable on Discord if you wanna see this issue closer. 
Here is my username and usertag: A user#8169

**Comment by abUwUser** [comment]
Also progress with my research: Woah, I've ran a Sensitive-Smart Mode scan and it didn't found the example comment that ive shown in it. Thats crazy...
![congratulations you hovered this image](https://user-images.githubusercontent.com/27961224/147165152-61478f7f-6fc5-4047-814f-74d1126003e0.png)
<sub>All of these are false positives</sub>

**Comment by themysticsavages** [comment]
Yeah, I know this is YouTube-Spammer-Purge, but these comments feel spam-like and some are just plain wrong.

**Comment by abUwUser** [comment]
They aren't. A lot of kids follow Felipe Neto, and like they send weird stuff sometimes. Very likely most of them are just kids beign kids. I can't verify it tho :/

**Comment by themysticsavages** [comment]
Maybe this script could use some translator API

**Comment by ThioJoe** [comment]
The app uses very few english words to decide on the spam, but if you see whatsapp spammers that look similar to the ones in English, feel free to share them and I can adjust it.

As for the emoji comments, those are not scams. Maybe at some point I'll add a "emoji spam" search mode specifically, but the app is designed to only find scammers. 

Also that 'false positive' you mention is absolutely not a false positive, that is a scammer. Look at the username.

I'll look into the other false positives, but the last one is probably because the person's username is too similar to the uploader's

**Comment by abUwUser** [comment]
Yeah, the whinderssonnunes' "false positive" is kinda a scammer as well, but its out of context. But well, still, whinderssonnunes is a 40+ million youtuber as well, so its kinda weird that it only found one.
I undestand your point about the emoji comments, but idk, its kinda annoying that there isn't a way to defend from those weird spammy comments. Maybe an option to the script filter repeated comments in a video, since they just copy and paste the same message in the same video arround multiple comments

**Comment by abUwUser** [comment]
I will close this, since now it isn't that much of a issue
