### ISSUE TITLE
unable to report extra spam comments

### ISSUE THREAD

**Issue by Freako76** [ThioJoe/YouTube-Spammer-Purge#177]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

![Screenshot 2021-12-22 185156](https://user-images.githubusercontent.com/95104389/147163935-08267eb6-bd5e-4974-ae01-ced32295c9ee.jpg)
so I was checking a video on youtube for more spam comments then I tried the Sensitive-Smart Mode to see if it picked up more spam comments (which it did) but then it failed to proceed with the reporting part. not sure if is on youtube's end or the program

### Release version

v2.2.2

### Steps to reproduce

1. Scan a Specific video
2. Sensitive-Smart Mode:
3. then issue

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
The deletion functionality was not enabled. Cannot delete or report comments.
Possible Cause: You're scanning someone elses video with a non-supported filter mode.
```

**Comment by abUwUser** [comment]
YTSP just lists the found users, but the functionality is disabled to prevent false alerts to be reported if you're not the channel owner

**Comment by Freako76** [comment]
> YTSP just lists the found users, but the functionality is disabled to prevent false alerts to be reported if you're not the channel owner

oh ok, it was working fine the second option then randomly it stopped working but ok

**Comment by ThioJoe** [comment]
Yea for now, only Auto Smart mode (not sensitive mode) can be used for reporting
