### ISSUE TITLE
Idea: use a list of spammer channel IDs to purge comments from multiple channels at once

### ISSUE THREAD

**Issue by MiguelGuthridge** [ThioJoe/YouTube-Spammer-Purge#18]
This should make it far quicker to remove comments from multiple accounts in one go, since the tool would be able to check for all of the accounts in the same amount of time, which will greatly improve efficiency of there's a ton of spammers.

If nobody beats me to it, I'll sort this out tomorrow morning, although I won't be able to test it myself since my channel (fortunately) isn't popular enough to get spam.

**Comment by ThioJoe** [comment]
Yea i plan to add this in probably the next release once i get around to it

**Comment by markviews** [comment]
@MiguelGuthridge you can give the program any video link even if you don't own it for testing

**Comment by ThioJoe** [comment]
Moving to discussion section: https://github.com/ThioJoe/YouTube-Spammer-Purge/discussions/39
