### ISSUE TITLE
Cannot detect Self Promoters

### ISSUE THREAD

**Issue by BraveGamerTV** [ThioJoe/YouTube-Spammer-Purge#215]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I saw spam comments on a video saying stuff like "<Channel Name> is bad im better" so I used the program to scan the video and it didn't detect a single one even though I could visibly see one. Every program has issues and this one is no different.

### Release version

2.2.5

### Steps to reproduce

It happens when I scan a video that has different types of spam comments.

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
Top Level Comments Scanned: 1084 | Replies Scanned: 627 | Matches Found So Far: 0

No matched comments or users found!

If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YouTube-Spammer-Purge/issues

Press Enter to exit...
```

**Comment by ThioJoe** [comment]
The program is focused on mass scams, not individual people leaving unique one-off comments

**Comment by BraveGamerTV** [comment]
Sorry,
