### ISSUE TITLE
Deprecation Error

### ISSUE THREAD

**Issue by iamflorencejay** [ThioJoe/YouTube-Spammer-Purge#22]
I think I've encountered an error when I run it on Linux, and the error traceback is here below:
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working from collections import Iterable

Traceback (most recent call last):
  File "/usr/bin/py", line 167, in <module>
    result = eval(args.expression)
  File "<string>", line 1, in <module>
    YouTubeSpammerPurge.py
NameError: name 'YouTubeSpammerPurge' is not defined
```

**Comment by ThioJoe** [comment]
I think the depreciation warning at the top is a separate unrelated thing to the actual error at the bottom line. 

For the error, what version of python are you running? And are you using one of the latest version of the script that has
`#!/usr/bin/env python3` at the top?

**Comment by iamflorencejay** [comment]
Yep.

**Comment by ThioJoe** [comment]
Did you try running it through the terminal?

**Comment by iamflorencejay** [comment]
> Did you try running it through the terminal? Some more details would be helpful because right now there's not really anything for me to do.

I'd run it to a terminal though.

**Comment by ThioJoe** [comment]
I'm thinking it has to do with your environment variables. It seems to be getting stuck up on the first line of the script which is the shebang at the very first line. Perhaps try changing that line from saying `python3` to just `python`?

Do you actually have python 3 installed?

Otherwise perhaps check out this stackoverflow thread: https://stackoverflow.com/questions/43793040/how-does-usr-bin-env-work-in-a-linux-shebang-line

You might want to try running `env` and see if it points to a directory with python.

**Comment by JojOatXGME** [comment]
@iamflorencejay What is `/usr/bin/py`? It looks like the issue is caused by this file.

**Comment by BioHazard1282** [comment]
That's an executable for Python in Linux




*----------------------------------------------*
*Floofy Wolf (BioHazard)*
*Senior at High School*
*Computer and Calculator programmer*

***@***.*** ***@***.***>*
*c3-productions.github.io <http://c3-productions.github.io/>*

**Comment by fgsi** [comment]
Apparently if you run `py` on a non-existant file it errors out that same way.
`DeprecationWarning` seems to always happen using it, though.
```
$ py osuhoaudhfidshfioahdf
/usr/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable
Traceback (most recent call last):
  File "/usr/bin/py", line 167, in <module>
    result = eval(args.expression)
  File "<string>", line 1, in <module>
    osuhoaudhfidshfioahdf
NameError: name 'osuhoaudhfidshfioahdf' is not defined
```
Can you try running it with `python` or `python3` instaed of `py`? Or just running it directly?

**Comment by iamflorencejay** [comment]
Trying rn

**Comment by Gowixx** [comment]
Contrary to popular belief, trying doesn't take 2 days

**Comment by TechStudent11** [comment]
So it's just a Linux/Unix issue. Because it isn't happening for me on Windows (11, but that doesn't make any difference).

**Comment by iamflorencejay** [comment]
> Contrary to popular belief, trying doesn't take 2 days

sorry bout that, it is now fixed on my end.

**Comment by Gowixx** [comment]
> sorry bout that, it is now fixed on my end.

Yeah, sorry for being toxic about it too lmao
