### ISSUE TITLE
[Bug]: (No module named request)

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YouTube-Spammer-Purge#229]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to run the program, and I pip install -r requirements.txt but then I got this error.

I know, its as easy to say pip install requests, but can't the module be added to the .txt file @ThioJoe ?

### Release version

2.2.6

### Steps to reproduce

1.  Pip install requirements.txt
2.  Run python

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "d:\Kendall\YouTube-Spammer-Purge-main\YouTubeSpammerPurge.py", line 43, in <module>
    from gui import *
  File "d:\Kendall\YouTube-Spammer-Purge-main\gui.py", line 5, in <module>
    import YouTubeSpammerPurge as myFunctions
  File "d:\Kendall\YouTube-Spammer-Purge-main\YouTubeSpammerPurge.py", line 54, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by KendallDoesCoding** [comment]
@ThioJoe I did pip install requests and got this:

Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages 
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (1.26.7)
PS D:\Kendall\YouTube-Spammer-Purge-main> & C:/Users/Admin/AppData/Local/Programs/Python/Python39/python.exe d:/Kendall/YouTube-Spammer-Purge-main/YouTubeSpammerPurge.py
  File "d:\Kendall\YouTube-Spammer-Purge-main\YouTubeSpammerPurge.py", line 43, in <module>
    from gui import *
  File "d:\Kendall\YouTube-Spammer-Purge-main\gui.py", line 5, in <module>
    import YouTubeSpammerPurge as myFunctions
  File "d:\Kendall\YouTube-Spammer-Purge-main\YouTubeSpammerPurge.py", line 54, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PS D:\Kendall\YouTube-Spammer-Purge-main> pip install requests
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages 
(from requests) (2.0.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.3)

**Comment by KendallDoesCoding** [comment]
Now that's weird, if its installed why is it saying No module named 'requests?

**Comment by rbeer** [comment]
Does the `c:\users\admin\appdata\local\programs\python\python310\lib\site-packages` path show up, when you simply run python and look at sys.path?

```python
>>> import sys
>>> sys.path
```

**Comment by KendallDoesCoding** [comment]
Yes, I didn't realize my python thing. I was using another interpreter which comes built in by a coding app. 

Closing this now.

@rbeer what do you mean by this?:

By the way, using
```powershell
copypasta
```
gives neat syntax highlighting for ps.

**Comment by rbeer** [comment]
https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

Using that with your copy/pasted output, gives:
```powershell
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (1.26.7)
PS D:\Kendall\YouTube-Spammer-Purge-main> & C:/Users/Admin/AppData/Local/Programs/Python/Python39/python.exe d:/Kendall/YouTube-Spammer-Purge-main/YouTubeSpammerPurge.py
File "d:\Kendall\YouTube-Spammer-Purge-main\YouTubeSpammerPurge.py", line 43, in
from gui import *
File "d:\Kendall\YouTube-Spammer-Purge-main\gui.py", line 5, in
import YouTubeSpammerPurge as myFunctions
File "d:\Kendall\YouTube-Spammer-Purge-main\YouTubeSpammerPurge.py", line 54, in
import requests
ModuleNotFoundError: No module named 'requests'
PS D:\Kendall\YouTube-Spammer-Purge-main> pip install requests
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages
(from requests) (2.0.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.3)
```

Much easier to read.

**Comment by KendallDoesCoding** [comment]
> https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting
> 
> Using that with your copy/pasted output and `powershell` as language identifier, gives:
> 
> ```powershell
> Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2.26.0)
> Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (2021.10.8)
> Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.3)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (1.26.7)
> PS D:\Kendall\YouTube-Spammer-Purge-main> & C:/Users/Admin/AppData/Local/Programs/Python/Python39/python.exe d:/Kendall/YouTube-Spammer-Purge-main/YouTubeSpammerPurge.py
> File "d:\Kendall\YouTube-Spammer-Purge-main\YouTubeSpammerPurge.py", line 43, in
> from gui import *
> File "d:\Kendall\YouTube-Spammer-Purge-main\gui.py", line 5, in
> import YouTubeSpammerPurge as myFunctions
> File "d:\Kendall\YouTube-Spammer-Purge-main\YouTubeSpammerPurge.py", line 54, in
> import requests
> ModuleNotFoundError: No module named 'requests'
> PS D:\Kendall\YouTube-Spammer-Purge-main> pip install requests
> Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (2.26.0)
> Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages
> (from requests) (2.0.9)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (1.26.7)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (2021.10.8)
> Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.3)
> ```
> 
> Much easier to read.

Thanks for the tool

**Comment by rbeer** [comment]
No problem :)
You can use all sorts of languages and file types

\```python
\```js
\```yaml
\```bash

and so on.

It's a small thing, but it often enough makes maintainers be more accepting of your issues and pull requests.

**Comment by KendallDoesCoding** [comment]
> No problem :) You can use all sorts of languages and file types
> 
> ```python ```js ```yaml ```bash
> 
> and so on.
> 
> It's a small thing, but it often enough makes maintainers be more accepting of your issues and pull requests.

Yeah, I knew about this coz the Bug report template has that, but I didnt know how I could do it. Now, I'll definitely use this. Thanks again :)
