### ISSUE TITLE
Idea - Would multithreading help? 

### ISSUE THREAD

**Issue by ageekhere** [ThioJoe/YouTube-Spammer-Purge#29]
Would multithreading help? or is the bottleneck the Google API?

Maybe for the delete message function the work could be split into threads.

amountOfWorkPerCore = NumberOfcores/numberOfMessages (there could be a rounding error so the last thread may need to account for that)
loop through NumberOfcores
thead deleteMessage(give range to delete)

However i am not sure if the bottleneck is the Google API.

Anyway just some brainstorming

**Comment by http403** [comment]
I believe the most time spend is waiting the API to return a response. I think async will be better in this case.

**Comment by SevastianGit** [comment]
I think that it would only help if a self-hosted version of the all would be made? #5
