### ISSUE TITLE
issue with deleting comments

### ISSUE THREAD

**Issue by BobWindows11** [ThioJoe/YouTube-Spammer-Purge#3]
hey i found an issue where i delete comments and it says possible issue i did everything right must be something about the video

**Comment by khaled-0** [comment]
Post some screenshots about what you got from the program in Terminal

**Comment by ThioJoe** [comment]
That error comes up if the API does not return an empty object when verifying a comment was deleted. Have you clicked the link or re-run the program to see if the comment is actually still there and didn't get deleted?

**Comment by KendallDoesCoding** [comment]
Hey @ThioJoe , even I'm having the same issue, I even disabled my anti firewall app for a while, but it's not working. Below is the error messege:

<HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/comments/setModerationStatus?id=UgzVI3OLpZyJZcx5NmF4AaABAg&moderationStatus=rejected returned "The API server failed to successfully process the request. While this can be a transient error, it usually indicates that the request's input is invalid.". Details: "[{'message': "The API server failed to successfully process the request. While this can be a transient error, it usually indicates that the request's input is invalid.", 'domain': 'youtube.comment', 'reason': 'processingFailure', 'location': 'id', 'locationType': 'parameter'}]">

**Comment by ThioJoe** [comment]
> Hey @ThioJoe , even I'm having the same issue, I even disabled my anti firewall app for a while, but it's not working. Below is the error messege:
> 
> 
> 
> <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/comments/setModerationStatus?id=UgzVI3OLpZyJZcx5NmF4AaABAg&moderationStatus=rejected returned "The API server failed to successfully process the request. While this can be a transient error, it usually indicates that the request's input is invalid.". Details: "[{'message': "The API server failed to successfully process the request. While this can be a transient error, it usually indicates that the request's input is invalid.", 'domain': 'youtube.comment', 'reason': 'processingFailure', 'location': 'id', 'locationType': 'parameter'}]">
> 
> 

That's a different error. Based on your other post I assume you are trying to delete comments on videos other than you own? Deleting comments requires the proper permissions and therefore can only be done on your own videos.

**Comment by KendallDoesCoding** [comment]
Oh ok, makes sense lol... Thanks

**Comment by ThioJoe** [comment]
Closing the issue because I believe original post was just a result of them trying to delete comments on a video they didn't have permission. The program now displays a warning if this is done.
