### ISSUE TITLE
Allow to add multiple spammer channel IDs at once

### ISSUE THREAD

**Issue by SevastianGit** [ThioJoe/YouTube-Spammer-Purge#31]
This would help in case if your channel/video has many different spammers, you just copy all of their IDs, put them into the software and delete all of their comments at once without having to repeat the scanning and deletion for every channel. Although Google's quota might be an issue.

**Comment by http403** [comment]
possible dup of #18

**Comment by SevastianGit** [comment]
> possible dup of #18
That issue talks about a **list** that anyone could use, my issue talks about a feature that you can add multiple channel IDs at once that you collect yourself, kinda different.

**Comment by http403** [comment]
Not to argue but if you talk about a community run list, that would be #15. Otherwise, I can't really see a different. List or not, just a choice of implementation that can be discussed later.

**Comment by KendallDoesCoding** [comment]
Well, you can just open the app 2 times, While this idea is cool, it may take lots of work to be added, but good idea ig.

**Comment by KendallDoesCoding** [comment]
Also what may happen is, that if you put a lot of channel ids, it may crash your computer depending on the model.
