### ISSUE TITLE
Simplifing the API access flow

### ISSUE THREAD

**Issue by http403** [ThioJoe/YouTube-Spammer-Purge#32]
I have encountered other projects that using a browser based OAuth flow to gain access to the user data. While there is a tutorial, most people didn't have experience in interacting and configuring Google Cloud. I suggest implementing a similar feature and lower the entry cost in using this tool which can benefit to more creators.

**Comment by ThioJoe** [comment]
I believe that would require self hosting the app. It's something I've been considering but haven't looked too much into implementing. 

See ( #5 )
