### ISSUE TITLE
Can anyone delete anyone's comments?

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YouTube-Spammer-Purge#33]
Hey @ThioJoe ,

This is a very good idea to put down scammers. 

Just was wondering, can't anyone delete any big channels's pinned comment or delete a big channel's comment? Or does it have a censor to determine if it's a scammers comment or no, because in your video it did work to delete your verified account's comment.

Would love to hear from you,
Kendall Does Coding

**Comment by ThioJoe** [comment]
Lol no of course not

**Comment by KendallDoesCoding** [comment]
> Lol no of course not

Ok lol
