### ISSUE TITLE
RegEx rule system

### ISSUE THREAD

**Issue by walking-octopus** [ThioJoe/YouTube-Spammer-Purge#45]
Allow a user to specify a local text file or an online URL with RegEx rules for blacklisting channel names, channel IDs, and comments as an argument.

Here's an example of a rule list.
```
// No arrow-up emoji in the channel name
channel_name: ⬆|🔼|🔺

// No comments with Bitcoin wallets in channel name or comment.
channel_name, comment: [13][a-km-zA-HJ-NP-Z1-9]{25,34}$

// No comments from ThioJoe
channel_id: ^UCQSpnDG3YsFNf5-qHocF-WQ
```

**Comment by ArjixWasTaken** [comment]
I don't see how using regex to filter channel IDs is useful...
But using a list of channel IDs instead of a single channel ID does sound better.

**Comment by walking-octopus** [comment]
RegEx can allow for more granular filtering. A rule set can contain RegEx to filter phone numbers, common obfuscation techniques, and more. As for filtering channel IDs, it might work as a replacement for channel list filtering.

**Comment by ArjixWasTaken** [comment]
If you reread my message, I only talked about the uselessness of regex for channel IDs
Since it would be more clean and make more sense to use a list instead.

I did not disagree or doubt that regex is useful for the other stuff.
Just the channel IDs
