### ISSUE TITLE
Just an idea...

### ISSUE THREAD

**Issue by reesericci** [ThioJoe/YouTube-Spammer-Purge#49]
It would be really cool if this used something like TensorFlow AI to automatically monitor the comments and delete them.

**Comment by TechStudent11** [comment]
Yeah, and maybe automatically delete spam comments when they get commented.

**Comment by TechStudent11** [comment]
But I don't think you can monitor YouTube videos with stuff like webhooks. So you would have to keep refreshing the current script I guess.
