### ISSUE TITLE
Self-Hosted Solution

### ISSUE THREAD

**Issue by abutlerboudakian** [ThioJoe/YouTube-Spammer-Purge#5]
Are there any plans at the moment to make this a self-hosted webapp (i.e. purchasing a domain and hosting a web version of this)? Having this tool available will be great for weeding out spammers but a lot of youtubers might not want to go through all the effort of generating their own API keys and running the console application manually, as well as possibly getting sussed out by all the security warnings that come up when downloading the compiled exe.

**Comment by ThioJoe** [comment]
I thought about it, and it definitely would be way easier to use, but I'd have to do a lot of research to figure out how to do that. Also the YouTube API has a relatively low initial quota and I'm not sure how hard it would be to get it increased sufficiently. I'll look into it, but don't really have any plans for it at the moment.

**Comment by arjun-dureja** [comment]
FYI, I've gotten my YouTube API quota increased from 25K per month to 500K per month pretty easily. I just had to submit a request explaining what my app did (mine was a simple sub count tracker) and why I needed a higher quota. They took about 3 weeks to get back to me.

**Comment by joaogelado** [comment]
> I thought about it, and it definitely would be way easier to use, but I'd have to do a lot of research to figure out how to do that. Also the YouTube API has a relatively low initial quota and I'm not sure how hard it would be to get it increased sufficiently. I'll look into it, but don't really have any plans for it at the moment.

If you do so, I recommend using vercel. It's like plug and play and it has a free plan that is good enough for starter projects. Also I like Next js (that is also from Vercel), but for this you will need learn JavaScript. Anyways, this is not a paid comment, it is just my opinions. Also, I am a programmer and use js for my projects. If you think I may help with something, you can try to call me out.

**Comment by ArjixWasTaken** [comment]
> FYI, I've gotten my YouTube API quota increased from 25K per month to 500K per month pretty easily. I just had to submit a request explaining what my app did (mine was a simple sub count tracker) and why I needed a higher quota. They took about 3 weeks to get back to me.

Easy solution is to use multiple API keys from multiple projects.

**Comment by deidyomega** [comment]
If you decide you want to go down that route, I'd be happy to help you do it. I've built more than a few webapps.

**Comment by SevastianGit** [comment]
> Easy solution is to use multiple API keys from multiple google cloud console projects.

Hmm, if that works and does increase the quota, maybe we should make a new issue to request this as a feature?
