### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by dwarfpuzzles** [ThioJoe/YouTube-Spammer-Purge#58]
I keep getting:

Error: Extra data: line 1 column 13 (char 12)

Something went wrong during authentication. Try deleting token.pickle file. Press Enter to exit...

**Comment by dwarfpuzzles** [comment]
Confirmed bug i see.

**Comment by ThioJoe** [comment]
Please give as many details as possible. Are you running the exe or the .py script? If the .py, what OS and python version?

Does this occur immediately on startup? Did it ever work? Does it  happen even when there is no token.pickle?

**Comment by dwarfpuzzles** [comment]
Exe.
Theres no token pickle generated.

**Comment by dwarfpuzzles** [comment]
OS is Windows 10 Professional.
64-bit.

**Comment by ThioJoe** [comment]
Hm ok, seems like there is an issue with this release, I'm also getting strange errors that weren't there before. I recommend just using the 1.3.3 version for now.

**Comment by ThioJoe** [comment]
Try the new 1.4.1 release. It probably won't fix your issue but it should print more info about the error that could be useful.

**Comment by dwarfpuzzles** [comment]
I'm using 1.4.1

**Comment by dwarfpuzzles** [comment]
still get*


The number increases the more time i open it.

**Comment by ThioJoe** [comment]
Which number do you mean?

Also, do you see anything that says "traceback" and then a bunch of stuff? Please copy and paste that text here. It probably looks something similar to this but maybe not exactly: 
<img width="725" alt="example" src="https://user-images.githubusercontent.com/12518330/140968258-0a1fd256-b66f-4aed-b1e2-b778f7ed41d8.png">

**Comment by dwarfpuzzles** [comment]
Error: Extra data: line 1 column 13 (char 12)

**Comment by dwarfpuzzles** [comment]
Seems like this is getting too deep frying..

Might be shown as a close to prevent confusion.

**Comment by dwarfpuzzles** [comment]
Mysteriously referred on 381.

**Comment by dwarfpuzzles** [comment]
.. also I think this is very old so I should keep this closed.. for now.
