### ISSUE TITLE
PyPI Package (pip) Command Line tool

### ISSUE THREAD

**Issue by Saketh-Chandra** [ThioJoe/YouTube-Spammer-Purge#6]
We can make a [PyPI package](https://pypi.org/) So that people can install it.
- like: `pip install YouTube-Spammer-Purge`.
- After installing the PIP (PyPI ) package
   -  simply people can type `YouTube-Spammer-Purge` in the terminal/CMD And the script will start.
   
If we do that, people can't get a Browser download warning or windows exe running warning.

I have some experience in making PIP in making python libraries.
- `Helloworldpy` is my simple PyPi (pip) package. we can run it through terminal [Source Code ](https://github.com/Saketh-Chandra/helloworldpy), [PyPI package link](https://pypi.org/project/helloworldpy/)

Can I make ` Pull Requests`? If implemented that feature?

**Comment by ThioJoe** [comment]
I'll just look into implementing it, I'd rather be able to learn to do it myself

**Comment by Saketh-Chandra** [comment]
Yeah fine!
