### ISSUE TITLE
It's made in python!

### ISSUE THREAD

**Issue by Snephanie** [ThioJoe/YouTube-Spammer-Purge#70]
Now see you might not see any issue with that but python is insanely slow, if someone could rewrite this in something a little bit faster like c# or Rust (or even Java) that would be beneficial.

**Comment by ThioJoe** [comment]
Ok

**Comment by Sizzukie** [comment]
> 
> Ok

no its not ok

**Comment by Snephanie** [comment]
ok

**Comment by KendallDoesCoding** [comment]
> Now see you might not see any issue with that but python is insanely slow, if someone could rewrite this in something a little bit faster like c# or Rust (or even Java) that would be beneficial.

Well, even I have issues with python, pip on one of my computers, it was fine before but now this became a issue, although if you just setup it properly it shouldn't create any issues as well as, if Python was slow 11.3M users wouldn't be using it. 

I don't think it is slow at all.

**Comment by Snephanie** [comment]
:trollface:
