### ISSUE TITLE
[Request/Idea] Async version

### ISSUE THREAD

**Issue by Gowixx** [ThioJoe/YouTube-Spammer-Purge#73]
I'm sure an async version would be a better option due to performance increases. I could look into it if I have time and maybe help out to move over to one.

**Comment by Gowixx** [comment]
After looking at the code, I don't think the googleapi has an async version, but maybe it will still speed it up

**Comment by TechStudent11** [comment]
Shouldn't this be a discussion rather than an issue?

**Comment by Gowixx** [comment]
My bad, https://github.com/ThioJoe/YouTube-Spammer-Purge/discussions/75
