### ISSUE TITLE
Making a GUI

### ISSUE THREAD

**Issue by JamesPerisher** [ThioJoe/YouTube-Spammer-Purge#76]
Hey  @ThioJoe 

I am wanted to make a PR to add a GUI

From experience getting a GUI to work without breaking cross-platform support is a little bit difficult and also requires a library in windows it is possible to use Tkinter however kivy is a more cross platform solution.  I have quite a bit of experience with kivy as can be seen here https://github.com/pauln07org/Kryptos as I have developed a full end2end encrypted messaging app using kivy.

I understand that you want to keep it simple so you can understand the code and this addition would add what can be considered complexity.

But as the contributing guidelines ask to open an issue before adding a new library or complicated code, please enlighten me with your thoughts on this.

**Comment by ThioJoe** [comment]
I tried making a GUI with Qt and failed miserably. I personally thought anything with tkinter looked like 1995, and kind of gave up.

I'm actually working on re-writing the entire script in C# / .NET so I can make a compiled cross platform version, especially with the new .NET MAUI framework (though it's still in beta). I'd hold off on starting it for now. I'll keep this open though and let you know what I decide to do. If I do decide to do the GUI with python, I may very well require your help.

**Comment by JamesPerisher** [comment]
In C# is asking for torture and I totally agree about tkinter being 1995 lol. If you where having issues doing it in python C# isn't going to be any easier trust me. I realy like the project so I'll spend an hour tomorrow most likely can get 95% complete in that time I'll open a PR just so u can look at my code.

**Comment by cob16** [comment]
In the far future would you want this to be a webpage/service?

I mention it as you could always run your GUI as a localhost webpage with plans to make it a hosted site in the future?
Not as cool as the options you have mentioned for sure but thought I might throw it out there

**Comment by Ahsoka** [comment]
I have a lot experience using PyQt6 so if you want to go that direction I would be happy to help.  See here for reference: https://github.com/Ahsoka/beskar

**Comment by Stridsvagn69420** [comment]
I believe porting the code to C# itself isn't that hard (e.g. there's an official .NET Google API library) but making the GUI is, and you would have to wait until 2nd quarter 2022 for .NET MAUI to officially be released.

My suggestion would be to make it hosted on the web or even a PWA (thus you basically have a GUI version for literally every platform) and/or use Electron for a cross-platform desktop GUI version that's also independent from any server.
It should be easy to make as well since the language in both cases is primarily JavaScript (although I recommend TypeScript).

**Comment by ThioJoe** [comment]
Converting to discussion
