### ISSUE TITLE
Code 400 - Processing Error

### ISSUE THREAD

**Issue by ThioJoe** [ThioJoe/YouTube-Spammer-Purge#85]
This error seems to have just started happening when deleting the comments, and seems to be a problem on YouTube's side. 
Multiple others are reporting the same error: https://issuetracker.google.com/u/1/issues/206873638

I've tested with older, known-working releases, as well as through Google's API playground with a request generated by YouTube's API demo page itself, and it still generates the error. Also tried it on multiple accounts.

If you are getting this error, try again after some time, and maybe check back here.

**CURRENT UPDATE:** It is now Tuesday, 4 days later, and the API is still broken... absurd.

**Comment by TechStudent11** [comment]
Maybe you should pin this so that if more issues come in, this is at the top.

**Comment by ThioJoe** [comment]
They're already aware and supposedly working on it

**Comment by KendallDoesCoding** [comment]
> They're already aware and supposedly working on it

Ok, hopefully it gets fixed soon :)

**Comment by KendallDoesCoding** [comment]
@ThioJoe Has this been fixed?

**Comment by TechStudent11** [comment]
@KendallDoesCoding don't think so. I've been getting emails about this but none of them say that it has been fixed.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding don't think so. I've been getting emails about this but none of them say that it has been fixed.

Ok, thanks!

**Comment by TechStudent11** [comment]
@ThioJoe @KendallDoesCoding Just looked at the issue. It appears to be fixed.

![image](https://user-images.githubusercontent.com/76978184/144046481-9d793066-e1be-4a0f-8eb8-0b4a60305d52.png)

**Comment by KendallDoesCoding** [comment]
Thanks for the update @TechStudent10, good to hear that!

Kindly close this issue thread.

**Comment by ThioJoe** [comment]
Issue has finally been fixed by Google
